/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author fields
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        lightOffBtn.setVisible(true);
        lightOnBtn.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lightOffBtn = new javax.swing.JButton();
        lightOnBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invernadero UTA Panel de Control");
        setMinimumSize(new java.awt.Dimension(980, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        lightOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/lightOff.png"))); // NOI18N
        lightOffBtn.setBorder(null);
        lightOffBtn.setBorderPainted(false);
        lightOffBtn.setContentAreaFilled(false);
        lightOffBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lightOffBtn.setFocusPainted(false);
        lightOffBtn.setMaximumSize(new java.awt.Dimension(160, 136));
        lightOffBtn.setMinimumSize(new java.awt.Dimension(160, 136));
        lightOffBtn.setOpaque(false);
        lightOffBtn.setPreferredSize(new java.awt.Dimension(160, 136));
        lightOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightOffBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lightOffBtn);
        lightOffBtn.setBounds(90, 80, 90, 160);

        lightOnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/lightOn.png"))); // NOI18N
        lightOnBtn.setBorderPainted(false);
        lightOnBtn.setContentAreaFilled(false);
        lightOnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lightOnBtn.setFocusPainted(false);
        lightOnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightOnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lightOnBtn);
        lightOnBtn.setBounds(90, 80, 90, 160);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel1.setText("Estatus");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 240, 70, 19);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/realTimeGraph.png"))); // NOI18N
        jButton1.setText("Tiempo Real");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 280, 160, 60);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/historic.png"))); // NOI18N
        jButton2.setText(" Histórico General   ");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 440, 280, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/lightSensor.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 100, 130, 130);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel3.setText("Sensor de Luz");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 70, 100, 19);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel4.setText("Lámpara:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 70, 17);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel5.setText("Estatus");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 240, 80, 19);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel6.setText("Luz:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 240, 30, 19);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/realTimeGraph.png"))); // NOI18N
        jButton3.setText("Tiempo Real");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 280, 160, 60);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/historic.png"))); // NOI18N
        jButton4.setText(" Histórico   ");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 350, 160, 60);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 10, 230, 17);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/tempSensor.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 100, 130, 130);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel9.setText("Sensor de Temperatura");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 70, 170, 19);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel10.setText("Estatus");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 240, 80, 19);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel11.setText("Temperatura:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 240, 90, 19);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/realTimeGraph.png"))); // NOI18N
        jButton5.setText("Tiempo Real");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 280, 160, 60);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/historic.png"))); // NOI18N
        jButton6.setText(" Histórico   ");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        getContentPane().add(jButton6);
        jButton6.setBounds(410, 350, 160, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/humiditySensor.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(600, 100, 130, 130);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel13.setText("Sensor de Humedad");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(600, 70, 170, 19);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel14.setText("Estatus");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(680, 240, 80, 19);

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel15.setText("Humedad:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(610, 240, 70, 19);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/realTimeGraph.png"))); // NOI18N
        jButton7.setText("Tiempo Real");
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        getContentPane().add(jButton7);
        jButton7.setBounds(590, 280, 160, 60);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/historic.png"))); // NOI18N
        jButton8.setText(" Histórico   ");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        getContentPane().add(jButton8);
        jButton8.setBounds(590, 350, 160, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/soilSensor.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(800, 100, 110, 130);

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel17.setText("Sensor de Humedad en Tierra");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(760, 70, 200, 19);

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel18.setText("Estatus");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(870, 240, 80, 19);

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel19.setText("Humedad:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(800, 240, 70, 19);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/realTimeGraph.png"))); // NOI18N
        jButton9.setText("Tiempo Real");
        jButton9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        getContentPane().add(jButton9);
        jButton9.setBounds(780, 280, 160, 60);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/historic.png"))); // NOI18N
        jButton10.setText(" Histórico   ");
        jButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        getContentPane().add(jButton10);
        jButton10.setBounds(780, 350, 160, 60);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/historic.png"))); // NOI18N
        jButton11.setText(" Histórico   ");
        jButton11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        getContentPane().add(jButton11);
        jButton11.setBounds(50, 350, 160, 60);

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel20.setText("Lámpara del Invernadero");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 70, 170, 19);

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel21.setText("Panel de Control");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(410, 20, 190, 29);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/logOut.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jButton12.setOpaque(false);
        getContentPane().add(jButton12);
        jButton12.setBounds(890, 0, 82, 58);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/logo_uta_mini.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        getContentPane().add(jButton13);
        jButton13.setBounds(10, 530, 210, 60);

        jButton14.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton14.setText("Made By Alberto Campos & Emiliano Roque");
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusPainted(false);
        getContentPane().add(jButton14);
        jButton14.setBounds(600, 550, 360, 40);

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel23.setText("Bienvenido");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 10, 100, 17);

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel24.setText("Usuario");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(110, 10, 230, 17);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/sensorsWall.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 970, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lightOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightOffBtnActionPerformed
        lightOnBtn.setVisible(true);
        lightOffBtn.setVisible(false);     
    }//GEN-LAST:event_lightOffBtnActionPerformed

    private void lightOnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightOnBtnActionPerformed
        lightOffBtn.setVisible(true);
        lightOnBtn.setVisible(false);  
    }//GEN-LAST:event_lightOnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton lightOffBtn;
    private javax.swing.JButton lightOnBtn;
    // End of variables declaration//GEN-END:variables
}
